version: '2'

services:
  mail:
    image: tophfr/mailcatcher:latest
    build: .
    ports:
      - 1080:80
  test:
    image: tophfr/dockerize:latest
    depends_on:
      - mail
    command: "-wait tcp://mail:25 sh -c 'echo \"Subject: bonjour de $$HOSTNAME\n\nca va bien ?\nbisou\" | sendmail -S mail aaa@zzz.eee'"

