version: '2'

services:
  mail:
    image: tophfr/mailcatcher
    build: .
    ports:
      - 1080:80
  test:
    image: busybox
    depends_on:
      - mail
    command: "sh -c 'echo \"Subject: bonjour\n\nca va bien ?\nbisou\" | sendmail -S mail aaa@zzz.eee'"

